/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BattleImport } from './routes/battle'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BattleRoute = BattleImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battle'
  id: '__root__' | '/' | '/battle'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/battle"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/battle": {
      "filePath": "battle.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
